# Generated by Django 4.1.3 on 2024-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoescola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoescola",
            name="cnpj",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
