# Generated by Django 4.1.3 on 2024-08-07 00:11

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):
    dependencies = [
        ("autoescola", "0002_alter_autoescola_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoescola",
            name="cnpj",
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
    ]
