# Generated by Django 4.1.3 on 2024-08-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoescola", "0003_alter_autoescola_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoescola",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Whatsapp (opcional)"
            ),
        ),
    ]
